# Generated by Django 5.2 on 2025-04-20 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="authors",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="books", to="book_app.author"
            ),
        ),
    ]
