# Generated by Django 5.2 on 2025-04-20 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book_app", "0002_alter_book_authors"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="book",
            name="unique_book",
        ),
        migrations.RemoveIndex(
            model_name="book",
            name="book_author_f8bd7b_idx",
        ),
        migrations.RemoveField(
            model_name="book",
            name="author",
        ),
        migrations.AlterField(
            model_name="book",
            name="authors",
            field=models.ManyToManyField(
                blank=True, related_name="books", to="book_app.author"
            ),
        ),
    ]
